# Generated by Django 5.2.1 on 2025-05-26 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsamaritan',
            name='forHowLong',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='goodsamaritan',
            name='gdSamaritanBenefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsamaritan',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grant'),
        ),
        migrations.AlterField(
            model_name='goodsamaritan',
            name='howItHelpedYou',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsamaritan',
            name='howMuch',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
