# Generated by Django 5.2.1 on 2025-05-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_goodsamaritan_forhowlong_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsamaritan',
            old_name='placeOfWaship',
            new_name='placeOfWorship',
        ),
    ]
