# Generated by Django 5.2.1 on 2025-06-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_placeofwaship_goodsamaritan_placeofworship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsamaritan',
            old_name='gdSamaritanBenefits',
            new_name='BenefitsFromgdSamaritan',
        ),
    ]
