# Generated by Django 5.2.1 on 2025-06-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_gdsamaritanbenefits_goodsamaritan_benefitsfromgdsamaritan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsamaritan',
            old_name='BenefitsFromgdSamaritan',
            new_name='BenefitsFromGoodSamaritan',
        ),
    ]
