# Generated by Django 5.2.1 on 2025-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_benefitsfromgdsamaritan_goodsamaritan_benefitsfromgoodsamaritan'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsamaritan',
            name='adviseToTheYouth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsamaritan',
            name='yourNeedFromGovtAsAGrand',
            field=models.TextField(blank=True, null=True),
        ),
    ]
