# Generated by Django 5.2.1 on 2025-07-19 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_goodsamaritan_advisetotheyouth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsamaritan',
            name='grant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.grant'),
        ),
    ]
