# Generated by Django 5.2.1 on 2025-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_goodsamaritan_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsamaritan',
            name='howMuch',
            field=models.FloatField(default=0),
        ),
    ]
